import _ from "lodash"
import { useMemo, useState } from "react"
import { NormalizationModes, NormalizationPrefixes, getAverageAndErrorByGroups, getQuantilesByGroups, groupListByProperty, normalizeDataToGroup } from "../../../../services/arrays/groupby"
import NormalizeIcon from "../../../core/svg/icons/chartSelection/Normalize"
import { useCycle } from "framer-motion"
import PlottypeIcon from "../../../core/svg/icons/chartSelection/Plottype"
import DownloadIcon from "../../../core/svg/icons/chartSelection/Download"
import { downloadTxtFile } from "../../../../services/downloads/txt"
import { arrayOfObjectsToString } from "../../../../services/arrays/transforms"
import { downloadSVG } from "../../../../services/downloads/svg"
import InfoIcon from "../../../core/svg/icons/chartSelection/Info"
import { useNavigate } from "react-router"
import { CategoricalChartSelection } from "./chartselection/CategoricalSelection"
import viz from "@mitocube/viz"
import { usePrefetchConditionApplicationTexts } from "@/api/orchestrated/conditionApplications"
import { usePrefetchAttributes } from "@/api/orchestrated/attributes"
PLACEHOLDER_REST_OF_FILE