
/**
 * Warning component about OpenAI generated content.
 * @returns {JSX.Element} Warning component about OpenAI generated content.
 */
export function OpenAIWarning() {

    return (
        <div
            role="note"
            style={{
                marginTop: "1rem",
                padding: "0.75rem 1rem",
                borderLeft: "4px solid #7a0000",
                borderRadius: "4px",
                backgroundColor: "#f5f6f7",
                color: "#333",
                marginBottom: "0.5rem",
            }}
        >
            <div style={{ display: "flex", gap: "0.6rem", alignItems: "center" }}>
                <span style={{ color: "#7a0000", fontWeight: 600, fontSize: "0.95rem" }}>Notice</span>
                <p style={{ margin: 0, fontSize: "0.95rem", color: "#4a4a4a" }}>
                    This content was generated by OpenAI's ChatGPT model or a similar LLM. It may contain inaccuracies (hallucinations).
                    Verify important information before relying on it.
                </p>
            </div>
        </div>
    )
}