
import _ from "lodash"
import { Combobox } from "../../core/input/Combobox"
import { Header } from "../../core/base/Header"
import { Select } from "@blueprintjs/select"
import { TagWithTooltip } from "../../core/base/tags/TagWithTooltip"
import { Button, InputGroup, Menu, MenuItem } from "@blueprintjs/core"
import { filterArrayBySearchString } from "../../../services/arrays/filter"
import SimpleTag from "../../core/base/tags/SimpleTag"
import NumericValueInput from "../../core/input/Numeric"
import { useState } from "react"
import DeleteButton from "../../core/base/buttons/DeleteButton"
import TextInput from "../../core/input/Text"


const attributes = {
    type: { name: "Gene Editing Type", tag: "att_gene_engineering" },
    method: { name: "Method", tag: "att_gene_engineering_method" },
    mutation: { name: "Mutation", tag: "att_gene_engineering_mutation" }
}

const fake_attributes = {
    type: [
        { name: "Knockout", tag: "att_gene_engineering: knockout", details : "Gene knock out"},
        { name: "Knockin", tag: "att_gene_engineering: knockin", details : "Gene knock in. One-for-one substitution of DNA sequence information in a genetic locus or the insertion of sequence information not found within the locus. "},
        { name: "Deletion", tag: "att_gene_engineering: deletion", details : "Gene deletion. "},
        { name: "Induc. expression", tag: "att_gene_engineering: indexpression" },
        { name: "Stable expression", tag: "att_gene_engineering: stableexpression" }],
    
    method: [{ name: "CRISPR-mediated", tag: "att_gene_engineering_method: CRISPR", details : "A CRISPR-associated (Cas) enzyme is used to cleave target DNA, resulting in a double-strand break (DSB). The Cas enzyme is directed by the guide RNA (gRNA) to a user-defined site in the genome, and then the Cas enzyme cuts the DNA."},
        { name: "CRSPR+HDR mediated", tag: "att_gene_engineering_method: CRISPR-HDR", details : "HDR is an acronym for homology-directed repair, one of the common mechanisms for DNA double-strand break repair in eukaryotes. HDR can be used as part of CRISPR-mediated editing to introduce an exogenous DNA repair template composed of homology arms flanking a sequence of interest."},
        { name: "BiggyBac transposon", tag: "att_gene_engineering_method: biggypac", details : "The PiggyBac (PB) transposon is a mobile genetic element that efficiently transposes between vectors and chromosomes via a 'cut and paste' mechanism. During transposition, the PB transposase recognizes transposon-specific inverted terminal repeat sequences (ITRs) located on both ends of the transposon vector and efficiently moves the contents from the original sites and integrates them into TTAA chromosomal sites"},
        { name: "TALE nucleases", tag: "att_gene_engineering_method: talenuclease", details : "Transcription activator-like effector nucleases (TALEN) are restriction enzymes that can be engineered to cut specific sequences of DNA. They are made by fusing a TAL effector DNA-binding domain to a DNA cleavage domain (a nuclease which cuts DNA strands). Transcription activator-like effectors (TALEs) can be engineered to bind to practically any desired DNA sequence, so when combined with a nuclease, DNA can be cut at specific locations."},
        { name: "Zinc-finger nucleases", tag: "att_gene_engineering_method: zincfingernuclease", details : "Zinc-finger nucleases (ZFNs) are artificial restriction enzymes generated by fusing a zinc finger DNA-binding domain to a DNA-cleavage domain. Zinc finger domains can be engineered to target specific desired DNA sequences and this enables zinc-finger nucleases to target unique sequences within complex genomes. "}],
    target: ["Fbxo30", "Oma1", "AFG3L2"],
    engineering: ["SNP", "Truncated", "Tagged"],
    mutation: [{ name: "AA Substitution", tag: "att_gene_engineering_mutation: substitution", details: "Amino acid exchange on a single amino acid position." },
        { name: "AA Deletion", tag: "att_gene_engineering_mutation: deletion", details: "Amino acid deletion on a single amino acid position." },
        { name: "Truncation", tag: "att_gene_engineering_mutation: truncation", details : "Deletion of a region in the amni acid sequence."}]
 }

const genotype = {
    gene_edits: [

    ],
    user_label : "asd2"
}




function AttributeSelection({attribute, attributeValues, selectedAttributeValue = undefined}) {

    const renderItem = (item, { handleClick, modifiers, index, query }) => {
        
        return <MenuItem key={item.tag} text={item.name} active={modifiers.active} disabled={modifiers.disabled} multiline={true} labelElement={<div style={{ width: "11rem", fontSize : "0.7rem" }}>{item.details}</div>} />
    }

    const filterItems = (query, items) => {
        if (query.length < 3) return items 
        const filteredItems = filterArrayBySearchString({ array:  items, searchString: query, searchColumns : ["tag","name","details"]})
        return filteredItems
    }
    return <Select
    popoverTargetProps = {{backgroundColor:"red"}}
        fill={false}
        items={attributeValues}
        itemListPredicate={filterItems}
        itemRenderer={renderItem}
        onItemSelect={item => console.log(item)}
        resetOnSelect={true}
    >
        
        <SimpleTag text={_.isObject(selectedAttributeValue)?selectedAttributeValue.name:attribute.name}/>
    </Select>
}


function AASequencePositionMutation({ }) {
    return (<div className="flex center-items">
        <AttributeSelection
            attribute={{ name: "wt AA", tag: "att_aa" }}
            attributeValues={[{ name: "Leucine", tag: "att_aa: L" }, { name: "Isoleucine", tag: "att_aa: I" }, { name: "Serine", tag: "att_aa: S" }]}
        />
        <NumericValueInput placeholder="Enter AA position ..."/>
        <AttributeSelection
            attribute={{ name: "mutant AA", tag: "att_aa" }}
            attributeValues={[{ name: "Leucine", tag: "att_aa: L" }, { name: "Isoleucine", tag: "att_aa: I" }, { name: "Serine", tag: "att_aa: S" }]}
        />
        </div>
    )
}


function AASequenceTruncation({ }) {
    return (<div className="flex center-items">
        <NumericValueInput placeholder="Start AA ..."/>
        <NumericValueInput placeholder="End AA ..." />
        </div>
    )
}



function Mutations({ }) {
    //mutation includes truncations/tags  

    return (
        <div>


        </div>
    )
}




function GenotypeRow({ }) {
    
    return (
        <div className="flex ">
            <AttributeSelection attribute={attributes.type} attributeValues={fake_attributes.type} />
            <AttributeSelection attribute={attributes.method} attributeValues={fake_attributes.method} />
            {/* <AttributeSelection attribute={attributes.method} attributeValues={fake_attributes.method} /> */}
            <div className="flex flex-column">


            </div>
            <InputGroup placeholder="Info / sequence ..." small={true} />
            
        </div>
    )
}


function GenotypeGenerator({index = 6 }) {
    const [n, setN] = useState(0)

    return (
        
        <div className="bg--lightgrey padding--medium div--round intent-margin-top--little">
            <Header text={`${index}. Genotypes`} />
            <p>Please specifiy your genotypes. This section requires you to provide an organism before to select specific target protein. You are able to specify amino acid mutations and truncations as well as tags. If you are just using wild types, for exmaple knock-down of a gene expression in just wild type cells does not require the definition of a genotype. </p>
            <p>Once you have defined your genotypes, you will have to assign them to each sample below in the sample attributes. Once you defined your genotypes you will not have to enter it again and it is available from the drop-down menu.</p>
            {_.range(n).map(idx => {
                return <div><div className="flex bg--white padding--little"><GenotypeRow /><Button icon="minus" intent="danger" small={true} minimal={true} /></div><Button icon="plus" small={true} minimal={true} intent="primary"/><hr /></div>
            })}
                    

            <Button icon="plus" onClick={() => setN(prevValue => prevValue + 1)} small={true} />
            
        </div>
    )
}


export default GenotypeGenerator