import hooks from "@mitocube/api-hooks";
import { apiClient } from "./client";
export const submissionAnalysisAPI = hooks.submissions.analysis.createSubmissionAnalysisAPI(apiClient);
export const submissionTitleAPI = hooks.submissions.title.createSubmissionTitleAPI(apiClient);
export const submissionCoreAPI = hooks.submissions.core.createSubmissionCoreAPI(apiClient);
export const submissionMetatextAPI = hooks.submissions.metatexts.createSubmissionMetatextAPI(apiClient);
export const submissionPermissionsAPI = hooks.submissions.permissions.createSubmissionPermissionsAPI(apiClient);
export const submissionStateAPI = hooks.submissions.states.createSubmissionStateAPI(apiClient);
export const submissionCAAPI = hooks.submissions.condition_applications.createSubmissionCAAPI(apiClient);
export const submissionCommentAPI = hooks.submissions.createSubmissionCommentsAPI(apiClient);
export const submissionCountAPI = hooks.submissions.counts.createSubmissionCountAPI(apiClient);
export const submissionQuantificationsAPI = hooks.submissions.quantifications.createSubmissionQuantificationAPI(apiClient);
export const submissionQueryAPI = hooks.submissions.query.createSubmissionQueryAPI(apiClient);
export const submissionRankingAPI = hooks.submissions.statistics.createSubmissionRankingAPI(apiClient);
export const submissionSamplesAPI = hooks.submissions.samples.createSubmissionSamplesAPI(apiClient);
export const submissionUserAPI = hooks.submissions.users.createSubmissionUsersAPI(apiClient);
export const submissionViewsAPI = hooks.submissions.views.createSubmissionViewsAPI(apiClient);
export const submissionRunlistAPI = hooks.submissions.runlist.createSubmissionRunlistAPI(apiClient);
export const submissionProtocolsAPI = hooks.submissions.protocols.createSubmissionProtocolsAPI(apiClient);